/***************************************************************************//**
* File Name: cycfg_gatt_db.c
* Version: 2.0
*
* Description:
* BLE device's GATT database and device configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.0.0 build 1231
*
********************************************************************************
* Copyright 2019 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_gatt_db.h"
#include "wiced_bt_uuid.h"
#include "wiced_bt_gatt.h"

/*************************************************************************************
* GATT server definitions
*************************************************************************************/

const uint8_t gatt_database[] =
{
    /* Primary Service: Generic Access */
    PRIMARY_SERVICE_UUID16 (HDLS_GAP, __UUID_SERVICE_GENERIC_ACCESS),
        /* Characteristic: Device Name */
        CHARACTERISTIC_UUID16 (HDLC_GAP_DEVICE_NAME, HDLC_GAP_DEVICE_NAME_VALUE, __UUID_CHARACTERISTIC_DEVICE_NAME, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Appearance */
        CHARACTERISTIC_UUID16 (HDLC_GAP_APPEARANCE, HDLC_GAP_APPEARANCE_VALUE, __UUID_CHARACTERISTIC_APPEARANCE, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),

    /* Primary Service: Generic Attribute */
    PRIMARY_SERVICE_UUID16 (HDLS_GATT, __UUID_SERVICE_GENERIC_ATTRIBUTE),

    /* Primary Service: Custom OTA Secure Firmware Upgrade */
    PRIMARY_SERVICE_UUID128 (HDLS_OTA_FW_UPGRADE_SERVICE, __UUID_SERVICE_CUSTOM_OTA_SECURE_FIRMWARE_UPGRADE),
        /* Characteristic: Control Point */
        CHARACTERISTIC_UUID128_WRITABLE (HDLC_OTA_FW_UPGRADE_SERVICE_CONTROL_POINT, HDLC_OTA_FW_UPGRADE_SERVICE_CONTROL_POINT_VALUE, __UUID_CHARACTERISTIC_CONTROL_POINT, LEGATTDB_CHAR_PROP_WRITE | LEGATTDB_CHAR_PROP_NOTIFY | LEGATTDB_CHAR_PROP_INDICATE, LEGATTDB_PERM_VARIABLE_LENGTH | LEGATTDB_PERM_WRITE_REQ),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_OTA_FW_UPGRADE_SERVICE_CONTROL_POINT_CLIENT_CHAR_CONFIG, __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ),
        /* Characteristic: Data */
        CHARACTERISTIC_UUID128_WRITABLE (HDLC_OTA_FW_UPGRADE_SERVICE_DATA, HDLC_OTA_FW_UPGRADE_SERVICE_DATA_VALUE, __UUID_CHARACTERISTIC_DATA, LEGATTDB_CHAR_PROP_WRITE, LEGATTDB_PERM_VARIABLE_LENGTH | LEGATTDB_PERM_WRITE_REQ),
};

/* Length of the GATT database */
const uint16_t gatt_database_len = sizeof(gatt_database);

/*************************************************************************************
 * GATT Initial Value Arrays
 ************************************************************************************/

uint8_t app_gap_device_name[]                                         = {'B', 'e', 'a', 'c', 'o', 'n', };
uint8_t app_gap_appearance[]                                          = {0x00, 0x02, };
uint8_t app_ota_fw_upgrade_service_control_point[]                    = {};
uint8_t app_ota_fw_upgrade_service_control_point_client_char_config[] = {0x00, 0x00, };
uint8_t app_ota_fw_upgrade_service_data[]                             = {};

 /************************************************************************************
 * GATT Lookup Table
 ************************************************************************************/

gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[] =
{
    /* { attribute handle,                                          maxlen, curlen, attribute data } */
    { HDLC_GAP_DEVICE_NAME_VALUE,                                   6,      6,      app_gap_device_name },
    { HDLC_GAP_APPEARANCE_VALUE,                                    2,      2,      app_gap_appearance },
    { HDLC_OTA_FW_UPGRADE_SERVICE_CONTROL_POINT_VALUE,              0,      0,      app_ota_fw_upgrade_service_control_point },
    { HDLD_OTA_FW_UPGRADE_SERVICE_CONTROL_POINT_CLIENT_CHAR_CONFIG, 2,      2,      app_ota_fw_upgrade_service_control_point_client_char_config },
    { HDLC_OTA_FW_UPGRADE_SERVICE_DATA_VALUE,                       0,      0,      app_ota_fw_upgrade_service_data },
};

/* Number of Lookup Table entries */
const uint16_t app_gatt_db_ext_attr_tbl_size = (sizeof(app_gatt_db_ext_attr_tbl) / sizeof(gatt_db_lookup_table_t));

/* Number of GATT initial value arrays entries */
const uint16_t app_gap_device_name_len = (sizeof(app_gap_device_name));
const uint16_t app_gap_appearance_len = (sizeof(app_gap_appearance));
const uint16_t app_ota_fw_upgrade_service_control_point_len = (sizeof(app_ota_fw_upgrade_service_control_point));
const uint16_t app_ota_fw_upgrade_service_control_point_client_char_config_len = (sizeof(app_ota_fw_upgrade_service_control_point_client_char_config));
const uint16_t app_ota_fw_upgrade_service_data_len = (sizeof(app_ota_fw_upgrade_service_data));
