/***************************************************************************//**
* File Name: cycfg_gatt_db.h
* Version: 2.1
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.1.0.2188
*
********************************************************************************
* Copyright 2020 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_GATT_DB_H)
#define CYCFG_GATT_DB_H

#include "stdint.h"

#define __UUID_SERVICE_GENERIC_ACCESS                      0x1800
#define __UUID_CHARACTERISTIC_DEVICE_NAME                  0x2A00
#define __UUID_CHARACTERISTIC_APPEARANCE                   0x2A01
#define __UUID_SERVICE_GENERIC_ATTRIBUTE                   0x1801
#define __UUID_SERVICE_ALERT_NOTIFICATION                  0x1811
#define __UUID_CHARACTERISTIC_SUPPORTED_NEW_ALERT_CATEGORY    0x2A47
#define __UUID_CHARACTERISTIC_NEW_ALERT                    0x2A46
#define __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION    0x2902
#define __UUID_CHARACTERISTIC_SUPPORTED_UNREAD_ALERT_CATEGORY    0x2A48
#define __UUID_CHARACTERISTIC_UNREAD_ALERT_STATUS          0x2A45
#define __UUID_CHARACTERISTIC_ALERT_NOTIFICATION_CONTROL_POINT    0x2A44

/* Service Generic Access */
#define HDLS_GAP                                           0x01
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                               0x02
#define HDLC_GAP_DEVICE_NAME_VALUE                         0x03
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                                0x04
#define HDLC_GAP_APPEARANCE_VALUE                          0x05

/* Service Generic Attribute */
#define HDLS_GATT                                          0x06

/* Service Alert Notification */
#define HDLS_ANS                                           0x07
/* Characteristic Supported New Alert Category */
#define HDLC_ANS_SUPPORTED_NEW_ALERT_CATEGORY              0x08
#define HDLC_ANS_SUPPORTED_NEW_ALERT_CATEGORY_VALUE        0x09
/* Characteristic New Alert */
#define HDLC_ANS_NEW_ALERT                                 0x0A
#define HDLC_ANS_NEW_ALERT_VALUE                           0x0B
/* Descriptor Client Characteristic Configuration */
#define HDLD_ANS_NEW_ALERT_CLIENT_CHAR_CONFIG              0x0C
/* Characteristic Supported Unread Alert Category */
#define HDLC_ANS_SUPPORTED_UNREAD_ALERT_CATEGORY           0x0D
#define HDLC_ANS_SUPPORTED_UNREAD_ALERT_CATEGORY_VALUE     0x0E
/* Characteristic Unread Alert Status */
#define HDLC_ANS_UNREAD_ALERT_STATUS                       0x0F
#define HDLC_ANS_UNREAD_ALERT_STATUS_VALUE                 0x10
/* Descriptor Client Characteristic Configuration */
#define HDLD_ANS_UNREAD_ALERT_STATUS_CLIENT_CHAR_CONFIG    0x11
/* Characteristic Alert Notification Control Point */
#define HDLC_ANS_ALERT_NOTIFICATION_CONTROL_POINT          0x12
#define HDLC_ANS_ALERT_NOTIFICATION_CONTROL_POINT_VALUE    0x13

/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_ans_supported_new_alert_category[];
extern const uint16_t app_ans_supported_new_alert_category_len;
extern uint8_t app_ans_new_alert[];
extern const uint16_t app_ans_new_alert_len;
extern uint8_t app_ans_new_alert_client_char_config[];
extern const uint16_t app_ans_new_alert_client_char_config_len;
extern uint8_t app_ans_supported_unread_alert_category[];
extern const uint16_t app_ans_supported_unread_alert_category_len;
extern uint8_t app_ans_unread_alert_status[];
extern const uint16_t app_ans_unread_alert_status_len;
extern uint8_t app_ans_unread_alert_status_client_char_config[];
extern const uint16_t app_ans_unread_alert_status_client_char_config_len;
extern uint8_t app_ans_alert_notification_control_point[];
extern const uint16_t app_ans_alert_notification_control_point_len;

#endif /* CYCFG_GATT_DB_H */
